#!/usr/bin/env python3
"""Enforce Go formatting, imports, declaration style, and style lint checks."""

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
from pathlib import Path


EXCLUDED_DIRS = {
    ".git",
    ".hg",
    ".svn",
    ".idea",
    ".vscode",
    "node_modules",
    "vendor",
    "third_party",
}

GOLANGCI_CONFIG = """# Generated by go-code-standards.
run:
  timeout: 5m
  tests: false

linters:
  enable:
    - gofmt
    - goimports
    - misspell
    - revive
    - whitespace

linters-settings:
  revive:
    rules:
      - name: exported
      - name: error-strings
      - name: error-naming
      - name: receiver-naming
      - name: var-naming
      - name: blank-imports

issues:
  exclude-use-default: false
"""


class CheckFailure(Exception):
    pass


def run(cmd: list[str], cwd: Path, *, capture: bool = False) -> subprocess.CompletedProcess[str]:
    print("+ " + " ".join(cmd))
    return subprocess.run(
        cmd,
        cwd=str(cwd),
        check=False,
        text=True,
        stdout=subprocess.PIPE if capture else None,
        stderr=subprocess.STDOUT if capture else None,
    )


def require_tool(name: str) -> str:
    path = shutil.which(name)
    if not path:
        raise CheckFailure(f"required tool not found on PATH: {name}")
    return path


def optional_tool(name: str, strict: bool) -> str | None:
    path = shutil.which(name)
    if path:
        return path
    if strict:
        raise CheckFailure(f"strict mode requires tool on PATH: {name}")
    print(f"[skip] {name} not found")
    return None


def go_files(repo: Path) -> list[Path]:
    files: list[Path] = []
    for root, dirs, names in os.walk(repo):
        dirs[:] = [d for d in dirs if d not in EXCLUDED_DIRS]
        for name in names:
            if name.endswith(".go"):
                files.append(Path(root, name))
    return sorted(files)


def rel_files(repo: Path, files: list[Path]) -> list[str]:
    return [str(path.relative_to(repo)) for path in files]


def check_or_fix_file_tool(tool: str, args: list[str], repo: Path, files: list[Path], fix: bool) -> None:
    if not files:
        return
    cmd = [tool, *args]
    if fix:
        cmd.append("-w")
    else:
        cmd.append("-l")
    cmd.extend(rel_files(repo, files))
    result = run(cmd, repo, capture=not fix)
    if result.returncode != 0:
        if result.stdout:
            print(result.stdout, end="")
        raise CheckFailure(f"{tool} failed")
    if not fix and result.stdout and result.stdout.strip():
        print(result.stdout, end="")
        raise CheckFailure(f"{tool} reported files that need formatting; rerun with --fix")


def read_optional(path: Path) -> bytes | None:
    return path.read_bytes() if path.exists() else None


def restore_optional(path: Path, data: bytes | None) -> None:
    if data is None:
        if path.exists():
            path.unlink()
        return
    path.write_bytes(data)


def check_go_mod_tidy(repo: Path, fix: bool) -> None:
    go_mod = repo / "go.mod"
    if not go_mod.exists():
        print("[skip] go.mod not found")
        return

    tracked = [go_mod, repo / "go.sum"]
    before = {path: read_optional(path) for path in tracked}
    result = run(["go", "mod", "tidy"], repo)
    if result.returncode != 0:
        raise CheckFailure("go mod tidy failed")
    after = {path: read_optional(path) for path in tracked}
    changed = [path.name for path in tracked if before[path] != after[path]]
    if changed and not fix:
        for path, data in before.items():
            restore_optional(path, data)
        raise CheckFailure("go mod tidy would change: " + ", ".join(changed))
    if changed:
        print("[fix] go mod tidy updated: " + ", ".join(changed))


def has_golangci_config(repo: Path) -> bool:
    names = (
        ".golangci.yml",
        ".golangci.yaml",
        ".golangci.toml",
        ".golangci.json",
    )
    return any((repo / name).exists() for name in names)


def write_golangci_config(repo: Path, overwrite: bool) -> None:
    target = repo / ".golangci.yml"
    if target.exists() and not overwrite:
        raise CheckFailure(".golangci.yml already exists; pass --overwrite-golangci-config to replace it")
    target.write_text(GOLANGCI_CONFIG, encoding="utf-8")
    print(f"[write] {target}")


def run_go_command(repo: Path, cmd: list[str], label: str) -> None:
    result = run(cmd, repo)
    if result.returncode != 0:
        raise CheckFailure(f"{label} failed")


def check_decl_order(repo: Path, include_tests: bool) -> None:
    script = Path(__file__).resolve().parent / "check_go_decl_order.go"
    cmd = ["go", "run", str(script), "--repo", str(repo)]
    if include_tests:
        cmd.append("--include-tests")
    result = run(cmd, repo)
    if result.returncode != 0:
        raise CheckFailure("Go declaration style check failed")


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default=".", help="Go repository path")
    parser.add_argument("--fix", action="store_true", help="rewrite formatting/imports")
    parser.add_argument("--strict", action="store_true", help="require goimports, gofumpt, and golangci-lint")
    parser.add_argument("--with-mod-tidy", action="store_true", help="also verify go mod tidy")
    parser.add_argument("--with-vet", action="store_true", help="also run go vet ./...")
    parser.add_argument("--with-tests", action="store_true", help="also run go test ./...")
    parser.add_argument("--skip-tests", action="store_true", help="deprecated no-op; tests are skipped by default")
    parser.add_argument("--race", action="store_true", help="run go test -race ./... when --with-tests is set")
    parser.add_argument("--skip-vet", action="store_true", help="deprecated no-op; vet is skipped by default")
    parser.add_argument("--skip-lint", action="store_true", help="skip golangci-lint")
    parser.add_argument("--skip-decl-order", action="store_true", help="skip declaration order and struct comment checks")
    parser.add_argument("--include-test-decls", action="store_true", help="include _test.go files in declaration style checks")
    parser.add_argument("--write-golangci-config", action="store_true", help="write starter .golangci.yml")
    parser.add_argument("--overwrite-golangci-config", action="store_true", help="replace existing .golangci.yml")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    repo = Path(args.repo).expanduser().resolve()
    if not repo.is_dir():
        print(f"repo is not a directory: {repo}", file=sys.stderr)
        return 2

    try:
        if args.write_golangci_config:
            write_golangci_config(repo, args.overwrite_golangci_config)

        require_tool("go")
        require_tool("gofmt")
        files = go_files(repo)
        if not files:
            print("[ok] no Go files found")
            return 0

        gofumpt = optional_tool("gofumpt", args.strict)
        goimports = optional_tool("goimports", args.strict)

        check_or_fix_file_tool(gofumpt or "gofmt", [], repo, files, args.fix)
        if goimports:
            check_or_fix_file_tool(goimports, [], repo, files, args.fix)

        if not args.skip_decl_order:
            check_decl_order(repo, args.include_test_decls)
        else:
            print("[skip] Go declaration style")

        if args.with_mod_tidy:
            check_go_mod_tidy(repo, args.fix)
        else:
            print("[skip] go mod tidy; style gate only")

        if args.with_vet:
            run_go_command(repo, ["go", "vet", "./..."], "go vet")
        else:
            print("[skip] go vet; style gate only")

        if args.with_tests:
            test_cmd = ["go", "test"]
            if args.race:
                test_cmd.append("-race")
            test_cmd.append("./...")
            run_go_command(repo, test_cmd, "go test")
        else:
            print("[skip] go test; style gate only")

        if not args.skip_lint:
            golangci = optional_tool("golangci-lint", args.strict or has_golangci_config(repo))
            if golangci:
                run_go_command(repo, [golangci, "run", "./..."], "golangci-lint")
        else:
            print("[skip] golangci-lint")

    except CheckFailure as exc:
        print(f"[fail] {exc}", file=sys.stderr)
        return 1

    print("[ok] Go style checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
